# Generated by Django 5.0.3 on 2024-08-30 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('detail', models.CharField(max_length=100)),
            ],
        ),
    ]
