# Generated by Django 5.1 on 2024-08-30 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0009_addcart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addcart',
            old_name='product',
            new_name='name',
        ),
    ]
