# Generated by Django 5.0.3 on 2024-09-05 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0012_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='name',
        ),
    ]
