# Generated by Django 5.0.3 on 2024-09-05 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0013_rename_product_order_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='subtotal',
        ),
    ]
