# Generated by Django 5.0.3 on 2024-09-23 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0013_bill_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ship_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_country', models.CharField(max_length=50)),
                ('ship_address', models.CharField(max_length=300)),
                ('ship_city', models.CharField(max_length=50)),
                ('ship_state', models.CharField(max_length=50)),
                ('ship_zip', models.CharField(max_length=6)),
                ('ship_phone', models.CharField(max_length=10)),
            ],
        ),
    ]
